package mint

// nolint
// autogenerated code using github.com/haasted/alias-generator.
// based on functionality in github.com/rigelrozanski/multitool

import (
	"github.com/bitsongofficial/go-bitsong/x/mint/keeper"
)

const ()

var (
	// functions aliases
	NewKeeper = keeper.NewKeeper

// variable aliases
)

type (
	Keeper = keeper.Keeper
)
