// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: bitsong/candymachine/candymachine.proto

package types

import (
	fmt "fmt"
	types "github.com/bitsongofficial/go-bitsong/x/nft/types"
	types1 "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/protobuf/types/known/durationpb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type CandyMachine struct {
	// id of the collection
	CollId uint64 `protobuf:"varint,1,opt,name=coll_id,json=collId,proto3" json:"coll_id,omitempty"`
	// mint price
	Price uint64 `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
	// wallet to receive payments
	Treasury string `protobuf:"bytes,3,opt,name=treasury,proto3" json:"treasury,omitempty"`
	// denom for the auction
	Denom string `protobuf:"bytes,4,opt,name=denom,proto3" json:"denom,omitempty"`
	// Timestamp when minting is allowed
	GoLiveDate uint64 `protobuf:"varint,5,opt,name=go_live_date,json=goLiveDate,proto3" json:"go_live_date,omitempty"`
	// mint end timestamp - not considered when set as 0
	EndTimestamp uint64 `protobuf:"varint,6,opt,name=end_timestamp,json=endTimestamp,proto3" json:"end_timestamp,omitempty"`
	// max mintable amount
	MaxMint uint64 `protobuf:"varint,7,opt,name=max_mint,json=maxMint,proto3" json:"max_mint,omitempty"`
	// minted amount
	Minted uint64 `protobuf:"varint,8,opt,name=minted,proto3" json:"minted,omitempty"`
	// owner of candy machine
	Authority string `protobuf:"bytes,9,opt,name=authority,proto3" json:"authority,omitempty"`
	// all metadata url is generated from metadata_base_url
	MetadataBaseUrl string `protobuf:"bytes,10,opt,name=metadata_base_url,json=metadataBaseUrl,proto3" json:"metadata_base_url,omitempty"`
	// mutability of the minted nfts
	Mutable bool `protobuf:"varint,11,opt,name=mutable,proto3" json:"mutable,omitempty"`
	// Royalty basis points that goes to creators in secondary sales (0-10000)
	SellerFeeBasisPoints uint32 `protobuf:"varint,12,opt,name=seller_fee_basis_points,json=sellerFeeBasisPoints,proto3" json:"seller_fee_basis_points,omitempty"`
	// Creators of metadata
	Creators []types.Creator `protobuf:"bytes,13,rep,name=creators,proto3" json:"creators"`
	// shows if ids are minted in sequence or shuffled
	Shuffle bool `protobuf:"varint,14,opt,name=shuffle,proto3" json:"shuffle,omitempty"`
}

func (m *CandyMachine) Reset()         { *m = CandyMachine{} }
func (m *CandyMachine) String() string { return proto.CompactTextString(m) }
func (*CandyMachine) ProtoMessage()    {}
func (*CandyMachine) Descriptor() ([]byte, []int) {
	return fileDescriptor_66f56f58d48d7759, []int{0}
}
func (m *CandyMachine) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CandyMachine) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CandyMachine.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CandyMachine) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CandyMachine.Merge(m, src)
}
func (m *CandyMachine) XXX_Size() int {
	return m.Size()
}
func (m *CandyMachine) XXX_DiscardUnknown() {
	xxx_messageInfo_CandyMachine.DiscardUnknown(m)
}

var xxx_messageInfo_CandyMachine proto.InternalMessageInfo

func (m *CandyMachine) GetCollId() uint64 {
	if m != nil {
		return m.CollId
	}
	return 0
}

func (m *CandyMachine) GetPrice() uint64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *CandyMachine) GetTreasury() string {
	if m != nil {
		return m.Treasury
	}
	return ""
}

func (m *CandyMachine) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func (m *CandyMachine) GetGoLiveDate() uint64 {
	if m != nil {
		return m.GoLiveDate
	}
	return 0
}

func (m *CandyMachine) GetEndTimestamp() uint64 {
	if m != nil {
		return m.EndTimestamp
	}
	return 0
}

func (m *CandyMachine) GetMaxMint() uint64 {
	if m != nil {
		return m.MaxMint
	}
	return 0
}

func (m *CandyMachine) GetMinted() uint64 {
	if m != nil {
		return m.Minted
	}
	return 0
}

func (m *CandyMachine) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *CandyMachine) GetMetadataBaseUrl() string {
	if m != nil {
		return m.MetadataBaseUrl
	}
	return ""
}

func (m *CandyMachine) GetMutable() bool {
	if m != nil {
		return m.Mutable
	}
	return false
}

func (m *CandyMachine) GetSellerFeeBasisPoints() uint32 {
	if m != nil {
		return m.SellerFeeBasisPoints
	}
	return 0
}

func (m *CandyMachine) GetCreators() []types.Creator {
	if m != nil {
		return m.Creators
	}
	return nil
}

func (m *CandyMachine) GetShuffle() bool {
	if m != nil {
		return m.Shuffle
	}
	return false
}

type MintableMetadataIds struct {
	CollectionId        uint64   `protobuf:"varint,1,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"`
	MintableMetadataIds []uint64 `protobuf:"varint,2,rep,packed,name=mintable_metadata_ids,json=mintableMetadataIds,proto3" json:"mintable_metadata_ids,omitempty"`
}

func (m *MintableMetadataIds) Reset()         { *m = MintableMetadataIds{} }
func (m *MintableMetadataIds) String() string { return proto.CompactTextString(m) }
func (*MintableMetadataIds) ProtoMessage()    {}
func (*MintableMetadataIds) Descriptor() ([]byte, []int) {
	return fileDescriptor_66f56f58d48d7759, []int{1}
}
func (m *MintableMetadataIds) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MintableMetadataIds) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MintableMetadataIds.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MintableMetadataIds) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MintableMetadataIds.Merge(m, src)
}
func (m *MintableMetadataIds) XXX_Size() int {
	return m.Size()
}
func (m *MintableMetadataIds) XXX_DiscardUnknown() {
	xxx_messageInfo_MintableMetadataIds.DiscardUnknown(m)
}

var xxx_messageInfo_MintableMetadataIds proto.InternalMessageInfo

func (m *MintableMetadataIds) GetCollectionId() uint64 {
	if m != nil {
		return m.CollectionId
	}
	return 0
}

func (m *MintableMetadataIds) GetMintableMetadataIds() []uint64 {
	if m != nil {
		return m.MintableMetadataIds
	}
	return nil
}

// Params defines candymachine module's parameters
type Params struct {
	CandymachineCreationPrice types1.Coin `protobuf:"bytes,1,opt,name=candymachine_creation_price,json=candymachineCreationPrice,proto3" json:"candymachine_creation_price" yaml:"candymachine_creation_price"`
	CandymachineMaxMint       uint64      `protobuf:"varint,2,opt,name=candymachine_max_mint,json=candymachineMaxMint,proto3" json:"candymachine_max_mint,omitempty"`
}

func (m *Params) Reset()      { *m = Params{} }
func (*Params) ProtoMessage() {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_66f56f58d48d7759, []int{2}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetCandymachineCreationPrice() types1.Coin {
	if m != nil {
		return m.CandymachineCreationPrice
	}
	return types1.Coin{}
}

func (m *Params) GetCandymachineMaxMint() uint64 {
	if m != nil {
		return m.CandymachineMaxMint
	}
	return 0
}

type EventCreateCandyMachine struct {
	Creator      string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	CollectionId uint64 `protobuf:"varint,2,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"`
}

func (m *EventCreateCandyMachine) Reset()         { *m = EventCreateCandyMachine{} }
func (m *EventCreateCandyMachine) String() string { return proto.CompactTextString(m) }
func (*EventCreateCandyMachine) ProtoMessage()    {}
func (*EventCreateCandyMachine) Descriptor() ([]byte, []int) {
	return fileDescriptor_66f56f58d48d7759, []int{3}
}
func (m *EventCreateCandyMachine) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventCreateCandyMachine) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventCreateCandyMachine.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventCreateCandyMachine) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventCreateCandyMachine.Merge(m, src)
}
func (m *EventCreateCandyMachine) XXX_Size() int {
	return m.Size()
}
func (m *EventCreateCandyMachine) XXX_DiscardUnknown() {
	xxx_messageInfo_EventCreateCandyMachine.DiscardUnknown(m)
}

var xxx_messageInfo_EventCreateCandyMachine proto.InternalMessageInfo

func (m *EventCreateCandyMachine) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *EventCreateCandyMachine) GetCollectionId() uint64 {
	if m != nil {
		return m.CollectionId
	}
	return 0
}

type EventUpdateCandyMachine struct {
	Creator      string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	CollectionId uint64 `protobuf:"varint,2,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"`
}

func (m *EventUpdateCandyMachine) Reset()         { *m = EventUpdateCandyMachine{} }
func (m *EventUpdateCandyMachine) String() string { return proto.CompactTextString(m) }
func (*EventUpdateCandyMachine) ProtoMessage()    {}
func (*EventUpdateCandyMachine) Descriptor() ([]byte, []int) {
	return fileDescriptor_66f56f58d48d7759, []int{4}
}
func (m *EventUpdateCandyMachine) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventUpdateCandyMachine) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventUpdateCandyMachine.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventUpdateCandyMachine) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventUpdateCandyMachine.Merge(m, src)
}
func (m *EventUpdateCandyMachine) XXX_Size() int {
	return m.Size()
}
func (m *EventUpdateCandyMachine) XXX_DiscardUnknown() {
	xxx_messageInfo_EventUpdateCandyMachine.DiscardUnknown(m)
}

var xxx_messageInfo_EventUpdateCandyMachine proto.InternalMessageInfo

func (m *EventUpdateCandyMachine) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *EventUpdateCandyMachine) GetCollectionId() uint64 {
	if m != nil {
		return m.CollectionId
	}
	return 0
}

type EventCloseCandyMachine struct {
	Creator      string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	CollectionId uint64 `protobuf:"varint,2,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"`
}

func (m *EventCloseCandyMachine) Reset()         { *m = EventCloseCandyMachine{} }
func (m *EventCloseCandyMachine) String() string { return proto.CompactTextString(m) }
func (*EventCloseCandyMachine) ProtoMessage()    {}
func (*EventCloseCandyMachine) Descriptor() ([]byte, []int) {
	return fileDescriptor_66f56f58d48d7759, []int{5}
}
func (m *EventCloseCandyMachine) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventCloseCandyMachine) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventCloseCandyMachine.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventCloseCandyMachine) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventCloseCandyMachine.Merge(m, src)
}
func (m *EventCloseCandyMachine) XXX_Size() int {
	return m.Size()
}
func (m *EventCloseCandyMachine) XXX_DiscardUnknown() {
	xxx_messageInfo_EventCloseCandyMachine.DiscardUnknown(m)
}

var xxx_messageInfo_EventCloseCandyMachine proto.InternalMessageInfo

func (m *EventCloseCandyMachine) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *EventCloseCandyMachine) GetCollectionId() uint64 {
	if m != nil {
		return m.CollectionId
	}
	return 0
}

type EventMintNFT struct {
	CollectionId uint64 `protobuf:"varint,1,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"`
	NftId        string `protobuf:"bytes,2,opt,name=nft_id,json=nftId,proto3" json:"nft_id,omitempty"`
}

func (m *EventMintNFT) Reset()         { *m = EventMintNFT{} }
func (m *EventMintNFT) String() string { return proto.CompactTextString(m) }
func (*EventMintNFT) ProtoMessage()    {}
func (*EventMintNFT) Descriptor() ([]byte, []int) {
	return fileDescriptor_66f56f58d48d7759, []int{6}
}
func (m *EventMintNFT) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventMintNFT) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventMintNFT.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventMintNFT) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventMintNFT.Merge(m, src)
}
func (m *EventMintNFT) XXX_Size() int {
	return m.Size()
}
func (m *EventMintNFT) XXX_DiscardUnknown() {
	xxx_messageInfo_EventMintNFT.DiscardUnknown(m)
}

var xxx_messageInfo_EventMintNFT proto.InternalMessageInfo

func (m *EventMintNFT) GetCollectionId() uint64 {
	if m != nil {
		return m.CollectionId
	}
	return 0
}

func (m *EventMintNFT) GetNftId() string {
	if m != nil {
		return m.NftId
	}
	return ""
}

func init() {
	proto.RegisterType((*CandyMachine)(nil), "bitsong.candymachine.v1beta1.CandyMachine")
	proto.RegisterType((*MintableMetadataIds)(nil), "bitsong.candymachine.v1beta1.MintableMetadataIds")
	proto.RegisterType((*Params)(nil), "bitsong.candymachine.v1beta1.Params")
	proto.RegisterType((*EventCreateCandyMachine)(nil), "bitsong.candymachine.v1beta1.EventCreateCandyMachine")
	proto.RegisterType((*EventUpdateCandyMachine)(nil), "bitsong.candymachine.v1beta1.EventUpdateCandyMachine")
	proto.RegisterType((*EventCloseCandyMachine)(nil), "bitsong.candymachine.v1beta1.EventCloseCandyMachine")
	proto.RegisterType((*EventMintNFT)(nil), "bitsong.candymachine.v1beta1.EventMintNFT")
}

func init() {
	proto.RegisterFile("bitsong/candymachine/candymachine.proto", fileDescriptor_66f56f58d48d7759)
}

var fileDescriptor_66f56f58d48d7759 = []byte{
	// 736 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0xbd, 0x6e, 0xdb, 0x3a,
	0x14, 0xb6, 0x62, 0xc7, 0x3f, 0x8c, 0x73, 0x2f, 0xae, 0xf2, 0xc7, 0xe4, 0xe6, 0xda, 0x86, 0xef,
	0x50, 0x23, 0x40, 0x2d, 0xc4, 0x45, 0x97, 0x0c, 0x1d, 0x9c, 0x36, 0x80, 0x8b, 0xba, 0x08, 0x84,
	0x04, 0x2d, 0xba, 0x08, 0xb4, 0x74, 0x24, 0x13, 0x90, 0x48, 0x43, 0xa4, 0x8c, 0xf8, 0x01, 0xba,
	0x77, 0xec, 0x98, 0xc7, 0xc9, 0x54, 0x64, 0xec, 0x14, 0x14, 0xc9, 0xd2, 0xb9, 0x4f, 0x50, 0x90,
	0x92, 0xec, 0xb8, 0x01, 0x8a, 0x0e, 0xd9, 0x78, 0xce, 0x77, 0xce, 0xc7, 0xf3, 0xf3, 0x91, 0xe8,
	0xc9, 0x88, 0x4a, 0xc1, 0x59, 0x60, 0xb9, 0x84, 0x79, 0xb3, 0x88, 0xb8, 0x63, 0xca, 0x60, 0xc9,
	0xe8, 0x4e, 0x62, 0x2e, 0xb9, 0xb9, 0x9f, 0x05, 0x76, 0x97, 0xb0, 0xe9, 0xe1, 0x08, 0x24, 0x39,
	0xdc, 0x6b, 0x06, 0x9c, 0x07, 0x21, 0x58, 0x3a, 0x76, 0x94, 0xf8, 0x96, 0xa4, 0x11, 0x08, 0x49,
	0xa2, 0x49, 0x9a, 0xbe, 0xd7, 0xf8, 0x35, 0xc0, 0x4b, 0x62, 0x22, 0x29, 0x67, 0x19, 0xbe, 0x19,
	0xf0, 0x80, 0xeb, 0xa3, 0xa5, 0x4e, 0x79, 0x96, 0xcb, 0x45, 0xc4, 0x85, 0x35, 0x22, 0x02, 0xac,
	0xec, 0x2e, 0xcb, 0xe5, 0x34, 0xcf, 0xfa, 0x2f, 0xaf, 0x9e, 0xf9, 0x72, 0x8e, 0x33, 0x5f, 0xa6,
	0x70, 0xfb, 0xa6, 0x88, 0xea, 0xc7, 0xaa, 0xdc, 0x61, 0x5a, 0xae, 0xb9, 0x83, 0x2a, 0x2e, 0x0f,
	0x43, 0x87, 0x7a, 0xd8, 0x68, 0x19, 0x9d, 0x92, 0x5d, 0x56, 0xe6, 0xc0, 0x33, 0x37, 0xd1, 0xea,
	0x24, 0xa6, 0x2e, 0xe0, 0x15, 0xed, 0x4e, 0x0d, 0x73, 0x0f, 0x55, 0x65, 0x0c, 0x44, 0x24, 0xf1,
	0x0c, 0x17, 0x5b, 0x46, 0xa7, 0x66, 0xcf, 0x6d, 0x95, 0xe1, 0x01, 0xe3, 0x11, 0x2e, 0x69, 0x20,
	0x35, 0xcc, 0x16, 0xaa, 0x07, 0xdc, 0x09, 0xe9, 0x14, 0x1c, 0x8f, 0x48, 0xc0, 0xab, 0x9a, 0x0e,
	0x05, 0xfc, 0x0d, 0x9d, 0xc2, 0x4b, 0x22, 0xc1, 0xfc, 0x1f, 0xad, 0x03, 0xf3, 0x9c, 0xf9, 0x7c,
	0x70, 0x59, 0x87, 0xd4, 0x81, 0x79, 0x67, 0xb9, 0xcf, 0xdc, 0x45, 0xd5, 0x88, 0x5c, 0x38, 0x11,
	0x65, 0x12, 0x57, 0x34, 0x5e, 0x89, 0xc8, 0xc5, 0x90, 0x32, 0x69, 0x6e, 0xa3, 0xb2, 0x72, 0x83,
	0x87, 0xab, 0x69, 0x07, 0xa9, 0x65, 0xee, 0xa3, 0x1a, 0x49, 0xe4, 0x98, 0xc7, 0x54, 0xce, 0x70,
	0x4d, 0xd7, 0xb4, 0x70, 0x98, 0x07, 0xe8, 0x9f, 0x08, 0x24, 0xf1, 0x88, 0x24, 0x8e, 0x1a, 0xa6,
	0x93, 0xc4, 0x21, 0x46, 0x3a, 0xea, 0xef, 0x1c, 0xe8, 0x13, 0x01, 0xe7, 0x71, 0x68, 0x62, 0x54,
	0x89, 0x12, 0x49, 0x46, 0x21, 0xe0, 0xb5, 0x96, 0xd1, 0xa9, 0xda, 0xb9, 0x69, 0x3e, 0x47, 0x3b,
	0x02, 0xc2, 0x10, 0x62, 0xc7, 0x07, 0x50, 0x3c, 0x54, 0x38, 0x13, 0x4e, 0x99, 0x14, 0xb8, 0xde,
	0x32, 0x3a, 0xeb, 0xf6, 0x66, 0x0a, 0x9f, 0x00, 0xf4, 0x15, 0x78, 0xaa, 0x31, 0xf3, 0x05, 0xaa,
	0xba, 0x31, 0x10, 0xc9, 0x63, 0x81, 0xd7, 0x5b, 0xc5, 0xce, 0x5a, 0x6f, 0xbf, 0x9b, 0xab, 0x49,
	0x2d, 0x2b, 0x5b, 0x5c, 0xf7, 0x38, 0x0d, 0xea, 0x97, 0xae, 0x6e, 0x9a, 0x05, 0x7b, 0x9e, 0xa3,
	0x0a, 0x12, 0xe3, 0xc4, 0xf7, 0x43, 0xc0, 0x7f, 0xa5, 0x05, 0x65, 0x66, 0x9b, 0xa1, 0x0d, 0x35,
	0x14, 0x55, 0xdc, 0x30, 0xeb, 0x62, 0xe0, 0x09, 0x35, 0x63, 0xb5, 0x57, 0x70, 0x95, 0xc0, 0x16,
	0xcb, 0xae, 0x2f, 0x9c, 0x03, 0xcf, 0xec, 0xa1, 0xad, 0x28, 0xcb, 0x75, 0xe6, 0xb3, 0xa1, 0x9e,
	0xc0, 0x2b, 0xad, 0x62, 0xa7, 0x64, 0x6f, 0x44, 0x0f, 0x89, 0xdb, 0x5f, 0x0c, 0x54, 0x3e, 0x25,
	0x31, 0x89, 0x84, 0xf9, 0xd1, 0x40, 0xff, 0xde, 0x7f, 0x0a, 0x8e, 0x2e, 0x57, 0xdd, 0x97, 0x0a,
	0x49, 0x5d, 0xb9, 0xd6, 0xdb, 0xed, 0xa6, 0x0a, 0xee, 0xaa, 0xa1, 0x2f, 0x1a, 0xe5, 0x94, 0xf5,
	0x0f, 0x54, 0x97, 0x3f, 0x6e, 0x9a, 0xed, 0x19, 0x89, 0xc2, 0xa3, 0xf6, 0x6f, 0xb8, 0xda, 0xf6,
	0xee, 0x7d, 0xf4, 0x38, 0x03, 0x4f, 0xb5, 0x46, 0x7b, 0x68, 0x6b, 0x29, 0x75, 0xae, 0x9b, 0x54,
	0xc9, 0x1b, 0xf7, 0xc1, 0x61, 0xaa, 0xa1, 0xa3, 0xea, 0xe7, 0xcb, 0x66, 0xe1, 0xfb, 0x65, 0xd3,
	0x68, 0xbf, 0x47, 0x3b, 0xaf, 0xa6, 0xc0, 0xa4, 0xe6, 0x84, 0xa5, 0xb7, 0x82, 0x51, 0x25, 0xdb,
	0x80, 0xee, 0xa5, 0x66, 0xe7, 0xe6, 0xc3, 0xf1, 0xae, 0x3c, 0x1c, 0xef, 0x9c, 0xf9, 0x7c, 0xe2,
	0x3d, 0x32, 0xf3, 0x3b, 0xb4, 0x9d, 0xd6, 0x1c, 0x72, 0xf1, 0xa8, 0xc4, 0xaf, 0x51, 0x5d, 0x13,
	0xab, 0x19, 0xbd, 0x3d, 0x39, 0xfb, 0x33, 0x19, 0x6d, 0xa1, 0x32, 0xf3, 0x65, 0x4e, 0x59, 0xb3,
	0x57, 0x99, 0x2f, 0x07, 0x5e, 0xff, 0xec, 0xea, 0xb6, 0x61, 0x5c, 0xdf, 0x36, 0x8c, 0x6f, 0xb7,
	0x0d, 0xe3, 0xd3, 0x5d, 0xa3, 0x70, 0x7d, 0xd7, 0x28, 0x7c, 0xbd, 0x6b, 0x14, 0x3e, 0x1c, 0x05,
	0x54, 0x8e, 0x93, 0x51, 0xd7, 0xe5, 0x91, 0x95, 0xbd, 0x02, 0xee, 0xfb, 0xd4, 0xa5, 0x24, 0xb4,
	0x02, 0xfe, 0x34, 0xff, 0xd1, 0x2e, 0x96, 0x7f, 0x64, 0x39, 0x9b, 0x80, 0x18, 0x95, 0xf5, 0xbf,
	0xf6, 0xec, 0x67, 0x00, 0x00, 0x00, 0xff, 0xff, 0x4a, 0x39, 0x63, 0x8c, 0xb6, 0x05, 0x00, 0x00,
}

func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.CandymachineCreationPrice.Equal(&that1.CandymachineCreationPrice) {
		return false
	}
	if this.CandymachineMaxMint != that1.CandymachineMaxMint {
		return false
	}
	return true
}
func (m *CandyMachine) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CandyMachine) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CandyMachine) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Shuffle {
		i--
		if m.Shuffle {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x70
	}
	if len(m.Creators) > 0 {
		for iNdEx := len(m.Creators) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Creators[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintCandymachine(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x6a
		}
	}
	if m.SellerFeeBasisPoints != 0 {
		i = encodeVarintCandymachine(dAtA, i, uint64(m.SellerFeeBasisPoints))
		i--
		dAtA[i] = 0x60
	}
	if m.Mutable {
		i--
		if m.Mutable {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x58
	}
	if len(m.MetadataBaseUrl) > 0 {
		i -= len(m.MetadataBaseUrl)
		copy(dAtA[i:], m.MetadataBaseUrl)
		i = encodeVarintCandymachine(dAtA, i, uint64(len(m.MetadataBaseUrl)))
		i--
		dAtA[i] = 0x52
	}
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintCandymachine(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0x4a
	}
	if m.Minted != 0 {
		i = encodeVarintCandymachine(dAtA, i, uint64(m.Minted))
		i--
		dAtA[i] = 0x40
	}
	if m.MaxMint != 0 {
		i = encodeVarintCandymachine(dAtA, i, uint64(m.MaxMint))
		i--
		dAtA[i] = 0x38
	}
	if m.EndTimestamp != 0 {
		i = encodeVarintCandymachine(dAtA, i, uint64(m.EndTimestamp))
		i--
		dAtA[i] = 0x30
	}
	if m.GoLiveDate != 0 {
		i = encodeVarintCandymachine(dAtA, i, uint64(m.GoLiveDate))
		i--
		dAtA[i] = 0x28
	}
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintCandymachine(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Treasury) > 0 {
		i -= len(m.Treasury)
		copy(dAtA[i:], m.Treasury)
		i = encodeVarintCandymachine(dAtA, i, uint64(len(m.Treasury)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Price != 0 {
		i = encodeVarintCandymachine(dAtA, i, uint64(m.Price))
		i--
		dAtA[i] = 0x10
	}
	if m.CollId != 0 {
		i = encodeVarintCandymachine(dAtA, i, uint64(m.CollId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MintableMetadataIds) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MintableMetadataIds) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MintableMetadataIds) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.MintableMetadataIds) > 0 {
		dAtA2 := make([]byte, len(m.MintableMetadataIds)*10)
		var j1 int
		for _, num := range m.MintableMetadataIds {
			for num >= 1<<7 {
				dAtA2[j1] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j1++
			}
			dAtA2[j1] = uint8(num)
			j1++
		}
		i -= j1
		copy(dAtA[i:], dAtA2[:j1])
		i = encodeVarintCandymachine(dAtA, i, uint64(j1))
		i--
		dAtA[i] = 0x12
	}
	if m.CollectionId != 0 {
		i = encodeVarintCandymachine(dAtA, i, uint64(m.CollectionId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CandymachineMaxMint != 0 {
		i = encodeVarintCandymachine(dAtA, i, uint64(m.CandymachineMaxMint))
		i--
		dAtA[i] = 0x10
	}
	{
		size, err := m.CandymachineCreationPrice.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintCandymachine(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *EventCreateCandyMachine) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventCreateCandyMachine) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventCreateCandyMachine) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CollectionId != 0 {
		i = encodeVarintCandymachine(dAtA, i, uint64(m.CollectionId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintCandymachine(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EventUpdateCandyMachine) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventUpdateCandyMachine) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventUpdateCandyMachine) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CollectionId != 0 {
		i = encodeVarintCandymachine(dAtA, i, uint64(m.CollectionId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintCandymachine(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EventCloseCandyMachine) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventCloseCandyMachine) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventCloseCandyMachine) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CollectionId != 0 {
		i = encodeVarintCandymachine(dAtA, i, uint64(m.CollectionId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintCandymachine(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EventMintNFT) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventMintNFT) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventMintNFT) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.NftId) > 0 {
		i -= len(m.NftId)
		copy(dAtA[i:], m.NftId)
		i = encodeVarintCandymachine(dAtA, i, uint64(len(m.NftId)))
		i--
		dAtA[i] = 0x12
	}
	if m.CollectionId != 0 {
		i = encodeVarintCandymachine(dAtA, i, uint64(m.CollectionId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintCandymachine(dAtA []byte, offset int, v uint64) int {
	offset -= sovCandymachine(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *CandyMachine) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.CollId != 0 {
		n += 1 + sovCandymachine(uint64(m.CollId))
	}
	if m.Price != 0 {
		n += 1 + sovCandymachine(uint64(m.Price))
	}
	l = len(m.Treasury)
	if l > 0 {
		n += 1 + l + sovCandymachine(uint64(l))
	}
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovCandymachine(uint64(l))
	}
	if m.GoLiveDate != 0 {
		n += 1 + sovCandymachine(uint64(m.GoLiveDate))
	}
	if m.EndTimestamp != 0 {
		n += 1 + sovCandymachine(uint64(m.EndTimestamp))
	}
	if m.MaxMint != 0 {
		n += 1 + sovCandymachine(uint64(m.MaxMint))
	}
	if m.Minted != 0 {
		n += 1 + sovCandymachine(uint64(m.Minted))
	}
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovCandymachine(uint64(l))
	}
	l = len(m.MetadataBaseUrl)
	if l > 0 {
		n += 1 + l + sovCandymachine(uint64(l))
	}
	if m.Mutable {
		n += 2
	}
	if m.SellerFeeBasisPoints != 0 {
		n += 1 + sovCandymachine(uint64(m.SellerFeeBasisPoints))
	}
	if len(m.Creators) > 0 {
		for _, e := range m.Creators {
			l = e.Size()
			n += 1 + l + sovCandymachine(uint64(l))
		}
	}
	if m.Shuffle {
		n += 2
	}
	return n
}

func (m *MintableMetadataIds) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.CollectionId != 0 {
		n += 1 + sovCandymachine(uint64(m.CollectionId))
	}
	if len(m.MintableMetadataIds) > 0 {
		l = 0
		for _, e := range m.MintableMetadataIds {
			l += sovCandymachine(uint64(e))
		}
		n += 1 + sovCandymachine(uint64(l)) + l
	}
	return n
}

func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.CandymachineCreationPrice.Size()
	n += 1 + l + sovCandymachine(uint64(l))
	if m.CandymachineMaxMint != 0 {
		n += 1 + sovCandymachine(uint64(m.CandymachineMaxMint))
	}
	return n
}

func (m *EventCreateCandyMachine) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovCandymachine(uint64(l))
	}
	if m.CollectionId != 0 {
		n += 1 + sovCandymachine(uint64(m.CollectionId))
	}
	return n
}

func (m *EventUpdateCandyMachine) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovCandymachine(uint64(l))
	}
	if m.CollectionId != 0 {
		n += 1 + sovCandymachine(uint64(m.CollectionId))
	}
	return n
}

func (m *EventCloseCandyMachine) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovCandymachine(uint64(l))
	}
	if m.CollectionId != 0 {
		n += 1 + sovCandymachine(uint64(m.CollectionId))
	}
	return n
}

func (m *EventMintNFT) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.CollectionId != 0 {
		n += 1 + sovCandymachine(uint64(m.CollectionId))
	}
	l = len(m.NftId)
	if l > 0 {
		n += 1 + l + sovCandymachine(uint64(l))
	}
	return n
}

func sovCandymachine(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozCandymachine(x uint64) (n int) {
	return sovCandymachine(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *CandyMachine) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCandymachine
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CandyMachine: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CandyMachine: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CollId", wireType)
			}
			m.CollId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCandymachine
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CollId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Price", wireType)
			}
			m.Price = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCandymachine
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Price |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Treasury", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCandymachine
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCandymachine
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCandymachine
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Treasury = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCandymachine
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCandymachine
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCandymachine
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field GoLiveDate", wireType)
			}
			m.GoLiveDate = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCandymachine
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.GoLiveDate |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndTimestamp", wireType)
			}
			m.EndTimestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCandymachine
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EndTimestamp |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxMint", wireType)
			}
			m.MaxMint = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCandymachine
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxMint |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Minted", wireType)
			}
			m.Minted = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCandymachine
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Minted |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCandymachine
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCandymachine
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCandymachine
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MetadataBaseUrl", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCandymachine
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCandymachine
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCandymachine
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MetadataBaseUrl = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Mutable", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCandymachine
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Mutable = bool(v != 0)
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SellerFeeBasisPoints", wireType)
			}
			m.SellerFeeBasisPoints = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCandymachine
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SellerFeeBasisPoints |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creators", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCandymachine
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCandymachine
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCandymachine
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creators = append(m.Creators, types.Creator{})
			if err := m.Creators[len(m.Creators)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 14:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Shuffle", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCandymachine
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Shuffle = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipCandymachine(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCandymachine
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MintableMetadataIds) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCandymachine
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MintableMetadataIds: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MintableMetadataIds: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CollectionId", wireType)
			}
			m.CollectionId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCandymachine
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CollectionId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType == 0 {
				var v uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowCandymachine
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.MintableMetadataIds = append(m.MintableMetadataIds, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowCandymachine
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthCandymachine
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthCandymachine
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.MintableMetadataIds) == 0 {
					m.MintableMetadataIds = make([]uint64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowCandymachine
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.MintableMetadataIds = append(m.MintableMetadataIds, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field MintableMetadataIds", wireType)
			}
		default:
			iNdEx = preIndex
			skippy, err := skipCandymachine(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCandymachine
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCandymachine
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CandymachineCreationPrice", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCandymachine
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCandymachine
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCandymachine
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CandymachineCreationPrice.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CandymachineMaxMint", wireType)
			}
			m.CandymachineMaxMint = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCandymachine
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CandymachineMaxMint |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipCandymachine(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCandymachine
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventCreateCandyMachine) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCandymachine
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventCreateCandyMachine: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventCreateCandyMachine: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCandymachine
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCandymachine
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCandymachine
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CollectionId", wireType)
			}
			m.CollectionId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCandymachine
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CollectionId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipCandymachine(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCandymachine
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventUpdateCandyMachine) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCandymachine
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventUpdateCandyMachine: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventUpdateCandyMachine: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCandymachine
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCandymachine
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCandymachine
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CollectionId", wireType)
			}
			m.CollectionId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCandymachine
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CollectionId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipCandymachine(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCandymachine
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventCloseCandyMachine) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCandymachine
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventCloseCandyMachine: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventCloseCandyMachine: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCandymachine
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCandymachine
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCandymachine
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CollectionId", wireType)
			}
			m.CollectionId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCandymachine
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CollectionId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipCandymachine(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCandymachine
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventMintNFT) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCandymachine
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventMintNFT: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventMintNFT: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CollectionId", wireType)
			}
			m.CollectionId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCandymachine
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CollectionId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NftId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCandymachine
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCandymachine
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCandymachine
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NftId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCandymachine(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCandymachine
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipCandymachine(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowCandymachine
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCandymachine
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCandymachine
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthCandymachine
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupCandymachine
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthCandymachine
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthCandymachine        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowCandymachine          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupCandymachine = fmt.Errorf("proto: unexpected end of group")
)
