package track

// nolint
// autogenerated code using github.com/haasted/alias-generator.
// based on functionality in github.com/rigelrozanski/multitool

import (
	"github.com/bitsongofficial/go-bitsong/x/track/client/cli"
	"github.com/bitsongofficial/go-bitsong/x/track/keeper"
	"github.com/bitsongofficial/go-bitsong/x/track/types"
)

const (
	QueryParams                = types.QueryParams
	QueryTracks                = types.QueryTracks
	QueryID                    = types.QueryID
	QueryCreatorTracks         = types.QueryCreatorTracks
	EventTypeTrackCreated      = types.EventTypeTrackCreated
	EventTypeTrackAddedShare   = types.EventTypeTrackAddedShare
	AttributeKeyTrackID        = types.AttributeKeyTrackID
	AttributeKeyTokenAmount    = types.AttributeKeyTokenAmount
	AttributeKeyTokenRecipient = types.AttributeKeyTokenRecipient
	TypeMsgTrackCreate         = types.TypeMsgTrackCreate
	TypeMsgTrackAddShare       = types.TypeMsgTrackAddShare
	ModuleName                 = types.ModuleName
	StoreKey                   = types.StoreKey
	RouterKey                  = types.RouterKey
	QuerierRoute               = types.QuerierRoute
	MaxTrackInfoLength         = types.MaxTrackInfoLength
)

var (
	// functions aliases
	GetTxCmd                    = cli.GetTxCmd
	GetCmdCreate                = cli.GetCmdCreate
	GetCmdAddShare              = cli.GetCmdAddShare
	GetQueryCmd                 = cli.GetQueryCmd
	GetCmdAll                   = cli.GetCmdAll
	GetCmdID                    = cli.GetCmdID
	GetCmdCreator               = cli.GetCmdCreator
	NewQuerier                  = keeper.NewQuerier
	NewKeeper                   = keeper.NewKeeper
	NewHandler                  = keeper.NewHandler
	NewQueryContentParams       = types.NewQueryContentParams
	DefaultQueryTracksParams    = types.DefaultQueryTracksParams
	RegisterCodec               = types.RegisterCodec
	NewGenesisState             = types.NewGenesisState
	DefaultGenesisState         = types.DefaultGenesisState
	ValidateGenesis             = types.ValidateGenesis
	NewMsgTrackCreate           = types.NewMsgTrackCreate
	NewMsgTrackAddShare         = types.NewMsgTrackAddShare
	NewTrack                    = types.NewTrack
	GetTrackIDBytes             = types.GetTrackIDBytes
	GetTrackKey                 = types.GetTrackKey
	GetCreatorKey               = types.GetCreatorKey
	GetTrackByCreatorAddr       = types.GetTrackByCreatorAddr
	GetTrackShareKey            = types.GetTrackShareKey
	GetSharesByTrackIDAndEntity = types.GetSharesByTrackIDAndEntity

	// variable aliases
	DefaultCodespace       = types.DefaultCodespace
	ModuleCdc              = types.ModuleCdc
	TrackKeyPrefix         = types.TrackKeyPrefix
	TracksCreatorKeyPrefix = types.TracksCreatorKeyPrefix
	TracksDepositKeyPrefix = types.TracksDepositKeyPrefix
)

type (
	Keeper                   = keeper.Keeper
	QueryCreatorTracksParams = types.QueryCreatorTracksParams
	QueryTrackParams         = types.QueryTrackParams
	QueryTracksParams        = types.QueryTracksParams
	Share                    = types.Share
	GenesisState             = types.GenesisState
	MsgTrackCreate           = types.MsgTrackCreate
	MsgTrackAddShare         = types.MsgTrackAddShare
	Entity                   = types.Entity
	Track                    = types.Track
)
