// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: bitsong/cadence/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgRegisterCadenceContract is the Msg/RegisterCadenceContract request type.
type MsgRegisterCadenceContract struct {
	// The address of the sender.
	SenderAddress string `protobuf:"bytes,1,opt,name=sender_address,json=senderAddress,proto3" json:"sender_address,omitempty"`
	// The address of the contract to register.
	ContractAddress string `protobuf:"bytes,2,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"`
}

func (m *MsgRegisterCadenceContract) Reset()         { *m = MsgRegisterCadenceContract{} }
func (m *MsgRegisterCadenceContract) String() string { return proto.CompactTextString(m) }
func (*MsgRegisterCadenceContract) ProtoMessage()    {}
func (*MsgRegisterCadenceContract) Descriptor() ([]byte, []int) {
	return fileDescriptor_50647315fd237ecd, []int{0}
}
func (m *MsgRegisterCadenceContract) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRegisterCadenceContract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRegisterCadenceContract.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRegisterCadenceContract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRegisterCadenceContract.Merge(m, src)
}
func (m *MsgRegisterCadenceContract) XXX_Size() int {
	return m.Size()
}
func (m *MsgRegisterCadenceContract) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRegisterCadenceContract.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRegisterCadenceContract proto.InternalMessageInfo

func (m *MsgRegisterCadenceContract) GetSenderAddress() string {
	if m != nil {
		return m.SenderAddress
	}
	return ""
}

func (m *MsgRegisterCadenceContract) GetContractAddress() string {
	if m != nil {
		return m.ContractAddress
	}
	return ""
}

// MsgRegisterCadenceContractResponse defines the response structure for executing a
// MsgRegisterCadenceContract message.
type MsgRegisterCadenceContractResponse struct {
}

func (m *MsgRegisterCadenceContractResponse) Reset()         { *m = MsgRegisterCadenceContractResponse{} }
func (m *MsgRegisterCadenceContractResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRegisterCadenceContractResponse) ProtoMessage()    {}
func (*MsgRegisterCadenceContractResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_50647315fd237ecd, []int{1}
}
func (m *MsgRegisterCadenceContractResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRegisterCadenceContractResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRegisterCadenceContractResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRegisterCadenceContractResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRegisterCadenceContractResponse.Merge(m, src)
}
func (m *MsgRegisterCadenceContractResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgRegisterCadenceContractResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRegisterCadenceContractResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRegisterCadenceContractResponse proto.InternalMessageInfo

// MsgUnregisterCadenceContract is the Msg/UnregisterCadenceContract request type.
type MsgUnregisterCadenceContract struct {
	// The address of the sender.
	SenderAddress string `protobuf:"bytes,1,opt,name=sender_address,json=senderAddress,proto3" json:"sender_address,omitempty"`
	// The address of the contract to unregister.
	ContractAddress string `protobuf:"bytes,2,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"`
}

func (m *MsgUnregisterCadenceContract) Reset()         { *m = MsgUnregisterCadenceContract{} }
func (m *MsgUnregisterCadenceContract) String() string { return proto.CompactTextString(m) }
func (*MsgUnregisterCadenceContract) ProtoMessage()    {}
func (*MsgUnregisterCadenceContract) Descriptor() ([]byte, []int) {
	return fileDescriptor_50647315fd237ecd, []int{2}
}
func (m *MsgUnregisterCadenceContract) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUnregisterCadenceContract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUnregisterCadenceContract.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUnregisterCadenceContract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUnregisterCadenceContract.Merge(m, src)
}
func (m *MsgUnregisterCadenceContract) XXX_Size() int {
	return m.Size()
}
func (m *MsgUnregisterCadenceContract) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUnregisterCadenceContract.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUnregisterCadenceContract proto.InternalMessageInfo

func (m *MsgUnregisterCadenceContract) GetSenderAddress() string {
	if m != nil {
		return m.SenderAddress
	}
	return ""
}

func (m *MsgUnregisterCadenceContract) GetContractAddress() string {
	if m != nil {
		return m.ContractAddress
	}
	return ""
}

// MsgUnregisterCadenceContractResponse defines the response structure for executing a
// MsgUnregisterCadenceContract message.
type MsgUnregisterCadenceContractResponse struct {
}

func (m *MsgUnregisterCadenceContractResponse) Reset()         { *m = MsgUnregisterCadenceContractResponse{} }
func (m *MsgUnregisterCadenceContractResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUnregisterCadenceContractResponse) ProtoMessage()    {}
func (*MsgUnregisterCadenceContractResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_50647315fd237ecd, []int{3}
}
func (m *MsgUnregisterCadenceContractResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUnregisterCadenceContractResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUnregisterCadenceContractResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUnregisterCadenceContractResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUnregisterCadenceContractResponse.Merge(m, src)
}
func (m *MsgUnregisterCadenceContractResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUnregisterCadenceContractResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUnregisterCadenceContractResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUnregisterCadenceContractResponse proto.InternalMessageInfo

// MsgUnjailCadenceContract is the Msg/UnjailCadenceContract request type.
type MsgUnjailCadenceContract struct {
	// The address of the sender.
	SenderAddress string `protobuf:"bytes,1,opt,name=sender_address,json=senderAddress,proto3" json:"sender_address,omitempty"`
	// The address of the contract to unjail.
	ContractAddress string `protobuf:"bytes,2,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"`
}

func (m *MsgUnjailCadenceContract) Reset()         { *m = MsgUnjailCadenceContract{} }
func (m *MsgUnjailCadenceContract) String() string { return proto.CompactTextString(m) }
func (*MsgUnjailCadenceContract) ProtoMessage()    {}
func (*MsgUnjailCadenceContract) Descriptor() ([]byte, []int) {
	return fileDescriptor_50647315fd237ecd, []int{4}
}
func (m *MsgUnjailCadenceContract) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUnjailCadenceContract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUnjailCadenceContract.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUnjailCadenceContract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUnjailCadenceContract.Merge(m, src)
}
func (m *MsgUnjailCadenceContract) XXX_Size() int {
	return m.Size()
}
func (m *MsgUnjailCadenceContract) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUnjailCadenceContract.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUnjailCadenceContract proto.InternalMessageInfo

func (m *MsgUnjailCadenceContract) GetSenderAddress() string {
	if m != nil {
		return m.SenderAddress
	}
	return ""
}

func (m *MsgUnjailCadenceContract) GetContractAddress() string {
	if m != nil {
		return m.ContractAddress
	}
	return ""
}

// MsgUnjailCadenceContractResponse defines the response structure for executing a
// MsgUnjailCadenceContract message.
type MsgUnjailCadenceContractResponse struct {
}

func (m *MsgUnjailCadenceContractResponse) Reset()         { *m = MsgUnjailCadenceContractResponse{} }
func (m *MsgUnjailCadenceContractResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUnjailCadenceContractResponse) ProtoMessage()    {}
func (*MsgUnjailCadenceContractResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_50647315fd237ecd, []int{5}
}
func (m *MsgUnjailCadenceContractResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUnjailCadenceContractResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUnjailCadenceContractResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUnjailCadenceContractResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUnjailCadenceContractResponse.Merge(m, src)
}
func (m *MsgUnjailCadenceContractResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUnjailCadenceContractResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUnjailCadenceContractResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUnjailCadenceContractResponse proto.InternalMessageInfo

// MsgUpdateParams is the Msg/UpdateParams request type.
//
// Since: cosmos-sdk 0.47
type MsgUpdateParams struct {
	// authority is the address of the governance account.
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	// params defines the x/cadence parameters to update.
	//
	// NOTE: All parameters must be supplied.
	Params Params `protobuf:"bytes,2,opt,name=params,proto3" json:"params"`
}

func (m *MsgUpdateParams) Reset()         { *m = MsgUpdateParams{} }
func (m *MsgUpdateParams) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParams) ProtoMessage()    {}
func (*MsgUpdateParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_50647315fd237ecd, []int{6}
}
func (m *MsgUpdateParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParams.Merge(m, src)
}
func (m *MsgUpdateParams) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParams) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParams.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParams proto.InternalMessageInfo

func (m *MsgUpdateParams) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgUpdateParams) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

// MsgUpdateParamsResponse defines the response structure for executing a
// MsgUpdateParams message.
//
// Since: cosmos-sdk 0.47
type MsgUpdateParamsResponse struct {
}

func (m *MsgUpdateParamsResponse) Reset()         { *m = MsgUpdateParamsResponse{} }
func (m *MsgUpdateParamsResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParamsResponse) ProtoMessage()    {}
func (*MsgUpdateParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_50647315fd237ecd, []int{7}
}
func (m *MsgUpdateParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParamsResponse.Merge(m, src)
}
func (m *MsgUpdateParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParamsResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgRegisterCadenceContract)(nil), "bitsong.cadence.v1.MsgRegisterCadenceContract")
	proto.RegisterType((*MsgRegisterCadenceContractResponse)(nil), "bitsong.cadence.v1.MsgRegisterCadenceContractResponse")
	proto.RegisterType((*MsgUnregisterCadenceContract)(nil), "bitsong.cadence.v1.MsgUnregisterCadenceContract")
	proto.RegisterType((*MsgUnregisterCadenceContractResponse)(nil), "bitsong.cadence.v1.MsgUnregisterCadenceContractResponse")
	proto.RegisterType((*MsgUnjailCadenceContract)(nil), "bitsong.cadence.v1.MsgUnjailCadenceContract")
	proto.RegisterType((*MsgUnjailCadenceContractResponse)(nil), "bitsong.cadence.v1.MsgUnjailCadenceContractResponse")
	proto.RegisterType((*MsgUpdateParams)(nil), "bitsong.cadence.v1.MsgUpdateParams")
	proto.RegisterType((*MsgUpdateParamsResponse)(nil), "bitsong.cadence.v1.MsgUpdateParamsResponse")
}

func init() { proto.RegisterFile("bitsong/cadence/v1/tx.proto", fileDescriptor_50647315fd237ecd) }

var fileDescriptor_50647315fd237ecd = []byte{
	// 570 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x94, 0x41, 0x4f, 0x13, 0x41,
	0x14, 0xc7, 0x3b, 0x88, 0x24, 0x8c, 0x0a, 0xba, 0x62, 0x68, 0x57, 0xdc, 0x96, 0x05, 0x54, 0x50,
	0x76, 0x04, 0x95, 0x10, 0x6e, 0x96, 0x73, 0xa3, 0xa9, 0xf1, 0xe2, 0x05, 0xa7, 0xdb, 0x61, 0x18,
	0xd3, 0x9d, 0xd9, 0xec, 0x4c, 0x09, 0xdc, 0x14, 0xe3, 0xdd, 0x84, 0x6f, 0xe0, 0xd1, 0x13, 0x31,
	0x7e, 0x08, 0x8e, 0x44, 0x2f, 0x9e, 0x8c, 0x69, 0x4d, 0xf8, 0x04, 0xde, 0x4d, 0x77, 0x66, 0x17,
	0xc5, 0x8e, 0xb1, 0x27, 0x2e, 0xcd, 0xf4, 0xbd, 0xff, 0x7b, 0xff, 0xdf, 0x6e, 0xfe, 0x3b, 0xf0,
	0x7a, 0x83, 0x29, 0x29, 0x38, 0x45, 0x21, 0x6e, 0x12, 0x1e, 0x12, 0xb4, 0xbd, 0x84, 0xd4, 0x4e,
	0x10, 0x27, 0x42, 0x09, 0xc7, 0x31, 0xcd, 0xc0, 0x34, 0x83, 0xed, 0x25, 0x77, 0x8a, 0x0a, 0x41,
	0x5b, 0x04, 0xe1, 0x98, 0x21, 0xcc, 0xb9, 0x50, 0x58, 0x31, 0xc1, 0xa5, 0x9e, 0x70, 0x27, 0x43,
	0x21, 0x23, 0x21, 0x51, 0x24, 0x69, 0x6f, 0x53, 0x24, 0xa9, 0x69, 0x54, 0xfa, 0xf8, 0x50, 0xc2,
	0x89, 0x64, 0xd9, 0xe8, 0x04, 0x15, 0x54, 0xa4, 0x47, 0xd4, 0x3b, 0x99, 0x6a, 0x49, 0x2f, 0xdc,
	0xd0, 0x0d, 0xfd, 0xc7, 0xb4, 0xae, 0xe0, 0x88, 0x71, 0x81, 0xd2, 0x5f, 0x5d, 0xf2, 0xdf, 0x00,
	0xe8, 0xd6, 0x24, 0xad, 0x13, 0xca, 0xa4, 0x22, 0xc9, 0xba, 0xf6, 0x5a, 0x17, 0x5c, 0x25, 0x38,
	0x54, 0xce, 0x1c, 0x1c, 0x93, 0x84, 0x37, 0x49, 0xb2, 0x81, 0x9b, 0xcd, 0x84, 0x48, 0x59, 0x04,
	0x15, 0x70, 0x7b, 0xb4, 0x7e, 0x49, 0x57, 0x1f, 0xe9, 0xa2, 0x33, 0x0f, 0x2f, 0x87, 0x66, 0x24,
	0x17, 0x0e, 0xa5, 0xc2, 0xf1, 0xac, 0x6e, 0xa4, 0x6b, 0x57, 0xf7, 0x8e, 0x0f, 0x16, 0x4e, 0x2d,
	0xf5, 0x67, 0xa1, 0x6f, 0x87, 0xa8, 0x13, 0x19, 0x0b, 0x2e, 0x89, 0xff, 0x16, 0xc0, 0xa9, 0x9a,
	0xa4, 0xcf, 0x78, 0x72, 0xb6, 0xb4, 0x37, 0xe1, 0xec, 0xbf, 0x30, 0x72, 0xde, 0xd7, 0x00, 0x16,
	0x53, 0xe1, 0x4b, 0xcc, 0x5a, 0x67, 0xc4, 0xea, 0xc3, 0x8a, 0x0d, 0x21, 0xe7, 0xdc, 0x07, 0x70,
	0xbc, 0x27, 0x8a, 0x9b, 0x58, 0x91, 0x27, 0x38, 0xc1, 0x91, 0x74, 0x56, 0xe0, 0x28, 0x6e, 0xab,
	0x2d, 0x91, 0x30, 0xb5, 0xab, 0xc9, 0xaa, 0xc5, 0xcf, 0x9f, 0x16, 0x27, 0x4c, 0x9e, 0x8c, 0xe7,
	0x53, 0x95, 0x30, 0x4e, 0xeb, 0x27, 0x52, 0x67, 0x15, 0x8e, 0xc4, 0xe9, 0x86, 0x94, 0xf2, 0xc2,
	0xb2, 0x1b, 0xfc, 0xfd, 0x45, 0x04, 0xda, 0xa3, 0x3a, 0x7c, 0xf8, 0xad, 0x5c, 0xa8, 0x1b, 0xfd,
	0xda, 0x58, 0x0f, 0xff, 0x64, 0x93, 0x5f, 0x82, 0x93, 0xa7, 0xa0, 0x32, 0xe0, 0xe5, 0x9f, 0xc3,
	0xf0, 0x5c, 0x4d, 0x52, 0xe7, 0x03, 0x80, 0x93, 0xb6, 0xe4, 0x06, 0xfd, 0x8c, 0xed, 0x21, 0x73,
	0x57, 0x06, 0xd3, 0xe7, 0x2f, 0xef, 0xd6, 0xde, 0x97, 0x1f, 0xfb, 0x43, 0xd3, 0x7e, 0x19, 0xf5,
	0xbd, 0x17, 0x50, 0x16, 0x12, 0xe7, 0x23, 0x80, 0x25, 0x7b, 0x74, 0xef, 0x59, 0xec, 0xad, 0x13,
	0xee, 0xea, 0xa0, 0x13, 0x39, 0xf2, 0x7c, 0x8a, 0x3c, 0xe3, 0x4f, 0x5b, 0x90, 0xdb, 0xf9, 0x06,
	0xe7, 0x3d, 0x80, 0xd7, 0xfa, 0xe7, 0xf7, 0xae, 0xd5, 0xbe, 0x8f, 0xda, 0x7d, 0x30, 0x88, 0x3a,
	0x07, 0x9d, 0x4b, 0x41, 0xcb, 0xfe, 0x0d, 0x2b, 0x68, 0x6f, 0xda, 0x79, 0x01, 0x2f, 0xfe, 0x91,
	0xdd, 0x19, 0x9b, 0xd9, 0x6f, 0x22, 0xf7, 0xce, 0x7f, 0x88, 0x32, 0x10, 0xf7, 0xfc, 0xab, 0xe3,
	0x83, 0x05, 0x50, 0x7d, 0x7c, 0xd8, 0xf1, 0xc0, 0x51, 0xc7, 0x03, 0xdf, 0x3b, 0x1e, 0x78, 0xd7,
	0xf5, 0x0a, 0x47, 0x5d, 0xaf, 0xf0, 0xb5, 0xeb, 0x15, 0x9e, 0x3f, 0xa4, 0x4c, 0x6d, 0xb5, 0x1b,
	0x41, 0x28, 0xa2, 0x8c, 0x55, 0x6c, 0x6e, 0xb2, 0x90, 0xe1, 0x16, 0xa2, 0x62, 0x31, 0xc3, 0xdf,
	0xc9, 0x1f, 0x40, 0xed, 0xc6, 0x44, 0x36, 0x46, 0xd2, 0x4b, 0xf8, 0xfe, 0xaf, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xe3, 0x0a, 0x13, 0x2a, 0x54, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// RegisterCadenceContract defines the endpoint for
	// registering a new cadence contract .
	RegisterCadenceContract(ctx context.Context, in *MsgRegisterCadenceContract, opts ...grpc.CallOption) (*MsgRegisterCadenceContractResponse, error)
	// UnregisterCadenceContract defines the endpoint for
	// unregistering a cadence contract .
	UnregisterCadenceContract(ctx context.Context, in *MsgUnregisterCadenceContract, opts ...grpc.CallOption) (*MsgUnregisterCadenceContractResponse, error)
	// UnjailCadenceContract defines the endpoint for
	// unjailing a cadence contract .
	UnjailCadenceContract(ctx context.Context, in *MsgUnjailCadenceContract, opts ...grpc.CallOption) (*MsgUnjailCadenceContractResponse, error)
	// UpdateParams defines a governance operation for updating the x/cadence module
	// parameters. The authority is hard-coded to the x/gov module account.
	//
	// Since: cosmos-sdk 0.47
	UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) RegisterCadenceContract(ctx context.Context, in *MsgRegisterCadenceContract, opts ...grpc.CallOption) (*MsgRegisterCadenceContractResponse, error) {
	out := new(MsgRegisterCadenceContractResponse)
	err := c.cc.Invoke(ctx, "/bitsong.cadence.v1.Msg/RegisterCadenceContract", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UnregisterCadenceContract(ctx context.Context, in *MsgUnregisterCadenceContract, opts ...grpc.CallOption) (*MsgUnregisterCadenceContractResponse, error) {
	out := new(MsgUnregisterCadenceContractResponse)
	err := c.cc.Invoke(ctx, "/bitsong.cadence.v1.Msg/UnregisterCadenceContract", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UnjailCadenceContract(ctx context.Context, in *MsgUnjailCadenceContract, opts ...grpc.CallOption) (*MsgUnjailCadenceContractResponse, error) {
	out := new(MsgUnjailCadenceContractResponse)
	err := c.cc.Invoke(ctx, "/bitsong.cadence.v1.Msg/UnjailCadenceContract", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error) {
	out := new(MsgUpdateParamsResponse)
	err := c.cc.Invoke(ctx, "/bitsong.cadence.v1.Msg/UpdateParams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// RegisterCadenceContract defines the endpoint for
	// registering a new cadence contract .
	RegisterCadenceContract(context.Context, *MsgRegisterCadenceContract) (*MsgRegisterCadenceContractResponse, error)
	// UnregisterCadenceContract defines the endpoint for
	// unregistering a cadence contract .
	UnregisterCadenceContract(context.Context, *MsgUnregisterCadenceContract) (*MsgUnregisterCadenceContractResponse, error)
	// UnjailCadenceContract defines the endpoint for
	// unjailing a cadence contract .
	UnjailCadenceContract(context.Context, *MsgUnjailCadenceContract) (*MsgUnjailCadenceContractResponse, error)
	// UpdateParams defines a governance operation for updating the x/cadence module
	// parameters. The authority is hard-coded to the x/gov module account.
	//
	// Since: cosmos-sdk 0.47
	UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) RegisterCadenceContract(ctx context.Context, req *MsgRegisterCadenceContract) (*MsgRegisterCadenceContractResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterCadenceContract not implemented")
}
func (*UnimplementedMsgServer) UnregisterCadenceContract(ctx context.Context, req *MsgUnregisterCadenceContract) (*MsgUnregisterCadenceContractResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnregisterCadenceContract not implemented")
}
func (*UnimplementedMsgServer) UnjailCadenceContract(ctx context.Context, req *MsgUnjailCadenceContract) (*MsgUnjailCadenceContractResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnjailCadenceContract not implemented")
}
func (*UnimplementedMsgServer) UpdateParams(ctx context.Context, req *MsgUpdateParams) (*MsgUpdateParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParams not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_RegisterCadenceContract_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRegisterCadenceContract)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RegisterCadenceContract(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bitsong.cadence.v1.Msg/RegisterCadenceContract",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RegisterCadenceContract(ctx, req.(*MsgRegisterCadenceContract))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UnregisterCadenceContract_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUnregisterCadenceContract)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UnregisterCadenceContract(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bitsong.cadence.v1.Msg/UnregisterCadenceContract",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UnregisterCadenceContract(ctx, req.(*MsgUnregisterCadenceContract))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UnjailCadenceContract_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUnjailCadenceContract)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UnjailCadenceContract(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bitsong.cadence.v1.Msg/UnjailCadenceContract",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UnjailCadenceContract(ctx, req.(*MsgUnjailCadenceContract))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bitsong.cadence.v1.Msg/UpdateParams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateParams(ctx, req.(*MsgUpdateParams))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bitsong.cadence.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterCadenceContract",
			Handler:    _Msg_RegisterCadenceContract_Handler,
		},
		{
			MethodName: "UnregisterCadenceContract",
			Handler:    _Msg_UnregisterCadenceContract_Handler,
		},
		{
			MethodName: "UnjailCadenceContract",
			Handler:    _Msg_UnjailCadenceContract_Handler,
		},
		{
			MethodName: "UpdateParams",
			Handler:    _Msg_UpdateParams_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bitsong/cadence/v1/tx.proto",
}

func (m *MsgRegisterCadenceContract) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRegisterCadenceContract) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRegisterCadenceContract) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ContractAddress) > 0 {
		i -= len(m.ContractAddress)
		copy(dAtA[i:], m.ContractAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ContractAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.SenderAddress) > 0 {
		i -= len(m.SenderAddress)
		copy(dAtA[i:], m.SenderAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.SenderAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgRegisterCadenceContractResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRegisterCadenceContractResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRegisterCadenceContractResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgUnregisterCadenceContract) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUnregisterCadenceContract) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUnregisterCadenceContract) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ContractAddress) > 0 {
		i -= len(m.ContractAddress)
		copy(dAtA[i:], m.ContractAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ContractAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.SenderAddress) > 0 {
		i -= len(m.SenderAddress)
		copy(dAtA[i:], m.SenderAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.SenderAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUnregisterCadenceContractResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUnregisterCadenceContractResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUnregisterCadenceContractResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgUnjailCadenceContract) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUnjailCadenceContract) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUnjailCadenceContract) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ContractAddress) > 0 {
		i -= len(m.ContractAddress)
		copy(dAtA[i:], m.ContractAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ContractAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.SenderAddress) > 0 {
		i -= len(m.SenderAddress)
		copy(dAtA[i:], m.SenderAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.SenderAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUnjailCadenceContractResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUnjailCadenceContractResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUnjailCadenceContractResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgUpdateParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgRegisterCadenceContract) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.SenderAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ContractAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgRegisterCadenceContractResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgUnregisterCadenceContract) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.SenderAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ContractAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgUnregisterCadenceContractResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgUnjailCadenceContract) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.SenderAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ContractAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgUnjailCadenceContractResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgUpdateParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Params.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgUpdateParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgRegisterCadenceContract) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRegisterCadenceContract: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRegisterCadenceContract: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SenderAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SenderAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContractAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContractAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRegisterCadenceContractResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRegisterCadenceContractResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRegisterCadenceContractResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUnregisterCadenceContract) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUnregisterCadenceContract: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUnregisterCadenceContract: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SenderAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SenderAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContractAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContractAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUnregisterCadenceContractResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUnregisterCadenceContractResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUnregisterCadenceContractResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUnjailCadenceContract) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUnjailCadenceContract: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUnjailCadenceContract: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SenderAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SenderAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContractAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContractAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUnjailCadenceContractResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUnjailCadenceContractResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUnjailCadenceContractResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
