package reward

// nolint
// autogenerated code using github.com/haasted/alias-generator.
// based on functionality in github.com/rigelrozanski/multitool

import (
	"github.com/bitsongofficial/go-bitsong/x/reward/keeper"
	"github.com/bitsongofficial/go-bitsong/x/reward/types"
)

const (
	DefaultParamspace = types.DefaultParamspace
	ModuleName        = types.ModuleName
	StoreKey          = types.StoreKey
	RouterKey         = types.RouterKey
	QueryRewards      = types.QueryRewards
)

var (
	// functions aliases
	NewReward         = types.NewReward
	RegisterCodec     = types.RegisterCodec
	RewardKey         = types.RewardKey
	InitialRewardPool = types.InitialRewardPool
	NewKeeper         = keeper.NewKeeper
	ParamKeyTable     = types.ParamKeyTable
	NewQuerier        = keeper.NewQuerier

	// variable aliases
	RewardPoolKey          = keeper.RewardPoolKey
	ParamStoreKeyRewardTax = types.ParamStoreKeyRewardTax
	ModuleCdc              = types.ModuleCdc
	RewardsKeyPrefix       = types.RewardsKeyPrefix
)

type (
	Keeper     = keeper.Keeper
	Reward     = types.Reward
	Rewards    = types.Rewards
	RewardPool = types.RewardPool
)
